In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [27]:
datos = pd.read_csv("data/Pokemon.csv", index_col="Number")
datos.head(10)

,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,Spe,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
Number,,,,,,,,,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1
2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0
3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,80,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0
3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,80,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0
4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,65,...,0.50,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6
5,Charmeleon,Fire,NaN,"['Blaze', 'Solar Power']",58,64,58,80,65,80,...,0.50,2.0,1.0,1.0,1.0,0.5,0.5,1.1,19.0,15.7
6,Charizard,Fire,Flying,"['Blaze', 'Solar Power']",78,84,78,109,85,100,...,0.25,4.0,1.0,1.0,1.0,0.5,0.5,1.7,90.5,31.3
6,Mega Charizard Y,Fire,Flying,['Drought'],78,104,78,159,115,100,...,0.25,4.0,1.0,1.0,1.0,0.5,0.5,1.7,100.5,34.8
6,Mega Charizard X,Fire,Dragon,['Tough Claws'],78,130,111,130,85,100,...,0.50,2.0,1.0,2.0,1.0,0.5,1.0,1.7,110.5,38.2
7,Squirtle,Water,NaN,"['Rain Dish', 'Torrent']",44,48,65,50,64,43,...,1.00,1.0,1.0,1.0,1.0,0.5,1.0,0.5,9.0,36.0

In [24]:
data.info()

<class 'pandas.DataFrame'>
Index: 1037 entries, 1 to 389
Data columns (total 43 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     1037 non-null   str
 1   Type 1                   1037 non-null   str
 2   Type 2                   551 non-null    str
 3   Abilities                1037 non-null   str
 4   HP                       1037 non-null   int64
 5   Att                      1037 non-null   int64
 6   Def                      1037 non-null   int64
 7   Spa                      1037 non-null   int64
 8   Spd                      1037 non-null   int64
 9   Spe                      1037 non-null   int64
 10  BST                      1037 non-null   int64
 11  Mean                     1037 non-null   float64
 12  Standard Deviation       1037 non-null   float64
 13  Generation               1037 non-null   float64
 14  Experience type          1037 non-null   str
 15  Experience to level 100  1037 non-null   int64
 16  Final Evolution          1037 non-null   float64
 17  Catch Rate               1037 non-null   int64
 18  Legendary                1037 non-null   float64
 19  Mega Evolution           1037 non-null   float64
 20  Alolan Form              1037 non-null   float64
 21  Galarian Form            1037 non-null   float64
 22  Against Normal           1037 non-null   float64
 23  Against Fire             1037 non-null   float64
 24  Against Water            1037 non-null   float64
 25  Against Electric         1037 non-null   float64
 26  Against Grass            1037 non-null   float64
 27  Against Ice              1037 non-null   float64
 28  Against Fighting         1037 non-null   float64
 29  Against Poison           1037 non-null   float64
 30  Against Ground           1037 non-null   float64
 31  Against Flying           1037 non-null   float64
 32  Against Psychic          1037 non-null   float64
 33  Against Bug              1037 non-null   float64
 34  Against Rock             1037 non-null   float64
 35  Against Ghost            1037 non-null   float64
 36  Against Dragon           1037 non-null   float64
 37  Against Dark             1037 non-null   float64
 38  Against Steel            1037 non-null   float64
 39  Against Fairy            1037 non-null   float64
 40  Height                   1037 non-null   float64
 41  Weight                   1037 non-null   float64
 42  BMI                      1037 non-null   float64
dtypes: float64(29), int64(9), str(5)
memory usage: 356.5 KB

In [23]:
data.isnull().any()

Name                       False
Type 1                     False
Type 2                      True
Abilities                  False
HP                         False
Att                        False
Def                        False
Spa                        False
Spd                        False
Spe                        False
BST                        False
Mean                       False
Standard Deviation         False
Generation                 False
Experience type            False
Experience to level 100    False
Final Evolution            False
Catch Rate                 False
Legendary                  False
Mega Evolution             False
Alolan Form                False
Galarian Form              False
Against Normal             False
Against Fire               False
Against Water              False
Against Electric           False
Against Grass              False
Against Ice                False
Against Fighting           False
Against Poison             False
Against Ground             False
Against Flying             False
Against Psychic            False
Against Bug                False
Against Rock               False
Against Ghost              False
Against Dragon             False
Against Dark               False
Against Steel              False
Against Fairy              False
Height                     False
Weight                     False
BMI                        False
dtype: bool

In [26]:
datos_sin_nulos= datos.dropna().copy()
datos_sin_nulos

,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,Spe,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
Number,,,,,,,,,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1
2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0
3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,80,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0
3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,80,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0
6,Charizard,Fire,Flying,"['Blaze', 'Solar Power']",78,84,78,109,85,100,...,0.25,4.0,1.0,1.0,1.0,0.5,0.5,1.7,90.5,31.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165,150,85,130,50,...,2.00,2.0,2.0,1.0,2.0,2.0,1.0,2.4,809.1,140.5
898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85,80,165,100,150,...,1.00,1.0,4.0,1.0,4.0,1.0,1.0,2.4,53.6,9.3
899,Alolan Raichu,Electric,Psychic,['Surge Surfer'],60,85,50,95,85,110,...,2.00,1.0,2.0,1.0,2.0,0.5,1.0,0.7,21.0,42.9
6,Charizard,Fire,Flying,"['Blaze', 'Solar Power']",78,84,78,109,85,100,...,0.25,4.0,1.0,1.0,1.0,0.5,0.5,1.7,90.5,31.3
389,Torterra,Grass,Ground,"['Overgrow', 'Shell Armor']",95,109,105,75,85,56,...,2.00,0.5,1.0,1.0,1.0,1.0,1.0,2.2,310.0,64.0

In [ ]:
datos.duplicated()

Number
1      False
2      False
3      False
3      False
4      False
       ...
899     True
900     True
25      True
6       True
389     True
Length: 1037, dtype: bool

In [31]:
datos_sin_dup= datos.drop_duplicates().copy()
datos_sin_dup

,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,Spe,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
Number,,,,,,,,,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1
2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0
3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,80,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0
3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,80,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0
4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,65,...,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,Glastrier,Ice,NaN,['Chilling Neigh'],100,145,130,65,110,30,...,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.2,800.0,165.3
897,Spectrier,Ghost,NaN,['Grim Neigh'],100,65,60,145,80,130,...,0.5,1.0,2.0,1.0,2.0,1.0,1.0,2.0,44.5,11.1
898,Calyrex,Psychic,Grass,['Unnerve'],100,80,80,80,80,80,...,4.0,1.0,2.0,1.0,2.0,1.0,1.0,1.1,7.7,6.4
898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165,150,85,130,50,...,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.4,809.1,140.5
898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85,80,165,100,150,...,1.0,1.0,4.0,1.0,4.0,1.0,1.0,2.4,53.6,9.3

In [36]:
datos_sin_nulos= datos_sin_dup.dropna().copy()
datos_sin_nulos

,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,Spe,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
Number,,,,,,,,,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,...,1.00,1.0,1.0,1.0,1.00,1.0,0.5,0.7,6.9,14.1
2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,...,1.00,1.0,1.0,1.0,1.00,1.0,0.5,1.0,13.0,13.0
3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,80,...,1.00,1.0,1.0,1.0,1.00,1.0,0.5,2.0,100.0,25.0
3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,80,...,1.00,1.0,1.0,1.0,1.00,1.0,0.5,2.4,155.5,27.0
6,Charizard,Fire,Flying,"['Blaze', 'Solar Power']",78,84,78,109,85,100,...,0.25,4.0,1.0,1.0,1.00,0.5,0.5,1.7,90.5,31.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892,Urshifu Single Strike Style,Fighting,Dark,['Unseen Fist'],100,130,100,63,60,97,...,1.00,0.5,0.5,1.0,0.25,1.0,4.0,1.9,105.0,29.1
893,Zarude,Dark,Grass,['Leaf Guard'],105,120,105,70,95,105,...,4.00,1.0,0.5,1.0,0.50,1.0,2.0,1.8,70.0,21.6
898,Calyrex,Psychic,Grass,['Unnerve'],100,80,80,80,80,80,...,4.00,1.0,2.0,1.0,2.00,1.0,1.0,1.1,7.7,6.4
898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165,150,85,130,50,...,2.00,2.0,2.0,1.0,2.00,2.0,1.0,2.4,809.1,140.5
898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85,80,165,100,150,...,1.00,1.0,4.0,1.0,4.00,1.0,1.0,2.4,53.6,9.3

In [55]:
def filtro_Fuego(Type):
    return 'Fire' in Type

datos_fuego = datos_sin_nulos[datos_sin_nulos['Type 1'].apply(filtro_Fuego)]

datos_fuego2= datos_sin_nulos[datos_sin_nulos['Type 2'].apply(filtro_Fuego)]

In [ ]:
tipo_fuego= datos_fuego[["Name", "Type 1", "Type 2"]]
tipo_fuego2= datos_fuego2[["Name", "Type 1", "Type 2"]]
tipo_fuego+tipo_fuego2

                                            Name    Type 1            Type 2
Number
6                             CharizardCharizard  FireFire      FlyingFlying
6               Mega Charizard YMega Charizard Y  FireFire      FlyingFlying
6               Mega Charizard XMega Charizard X  FireFire      DragonDragon
105                 Alolan MarowakAlolan Marowak  FireFire        GhostGhost
146                               MoltresMoltres  FireFire      FlyingFlying
219                             MagcargoMagcargo  FireFire          RockRock
250                                   Ho-OhHo-Oh  FireFire      FlyingFlying
256                           CombuskenCombusken  FireFire  FightingFighting
257                             BlazikenBlaziken  FireFire  FightingFighting
257                   Mega BlazikenMega Blaziken  FireFire  FightingFighting
322                                   NumelNumel  FireFire      GroundGround
323                             CameruptCamerupt  FireFire      GroundGround
323                   Mega CameruptMega Camerupt  FireFire      GroundGround
391                             MonfernoMonferno  FireFire  FightingFighting
392                           InfernapeInfernape  FireFire  FightingFighting
485                               HeatranHeatran  FireFire        SteelSteel
499                               PignitePignite  FireFire  FightingFighting
500                                 EmboarEmboar  FireFire  FightingFighting
555       Darmanitan Zen-ModeDarmanitan Zen-Mode  FireFire    PsychicPsychic
655                               DelphoxDelphox  FireFire    PsychicPsychic
662                       FletchinderFletchinder  FireFire      FlyingFlying
663                         TalonflameTalonflame  FireFire      FlyingFlying
667                                 LitleoLitleo  FireFire      NormalNormal
668                                 PyroarPyroar  FireFire      NormalNormal
721                           VolcanionVolcanion  FireFire        WaterWater
727                         IncineroarIncineroar  FireFire          DarkDark
741     Oricorio Baile StyleOricorio Baile Style  FireFire      FlyingFlying
776                         TurtonatorTurtonator  FireFire      DragonDragon
806                       BlacephalonBlacephalon  FireFire        GhostGhost
850                         SizzlipedeSizzlipede  FireFire            BugBug
851                       CentiskorchCentiskorch  FireFire            BugBug